spring:
  application:
    name: chess
  datasource:
    url: jdbc:postgresql://localhost:5432/chess
    username: eskil
    password: password

app:
  jwt:
    secret: ${JWT_SECRET:superSecretKeyForTheDevelopmentWhichIsAbsolutelySecureEnoughAndFarEnoughBitsToBeAbleToBeMadeIntoASecureEnoughKey}