spring:
  application:
    name: chess
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chess}
    username: ${SPRING_DATASOURCE_USERNAME:eskil}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://localhost:6379}
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholders:
      admin_password: ${ADMIN_PASSWORD:$2y$12$Sr02udJa6JObVAJnma46gedjUtHZKh70.hdpn7j6uLJQtKc44IgTW}

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  jwt:
    secret: ${JWT_SECRET:superSecretKeyForTheDevelopmentWhichIsAbsolutelySecureEnoughAndFarEnoughBitsToBeAbleToBeMadeIntoASecureEnoughKey}

rate-limit:
  login:
    max-tokens: ${LOGIN_TOKENS:1000}
  register:
    max-tokens: ${REGISTER_TOKENS:1000}
  other:
    max-tokens: ${OTHER_TOKENS:1000}