spring:
  application:
    name: chess
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chess}
    username: ${spring.datasource.username:postgres}
    password: ${spring.datasource.password:password}

app:
  jwt:
    secret: ${JWT_SECRET:superSecretKeyForTheDevelopmentWhichIsAbsolutelySecureEnoughAndFarEnoughBitsToBeAbleToBeMadeIntoASecureEnoughKey}