ALTER TABLE users ADD COLUMN role VARCHAR(255) DEFAULT 'USER'
    CONSTRAINT role_check CHECK (role IN ('SUPERUSER', 'ADMIN', 'MODERATOR', 'TRUSTED', 'USER'));
ALTER TABLE users ADD COLUMN games INT DEFAULT 0;
ALTER TABLE users ADD COLUMN been2400 bool DEFAULT false;