ALTER TABLE users
    RENAME COLUMN avatarurl TO avatar_url;

ALTER TABLE users
    DROP COLUMN elo;
ALTER TABLE users
    DROP COLUMN been2400;
ALTER TABLE users
    DROP COLUMN games;

ALTER TABLE users
    ADD COLUMN bullet_elo INT NOT NULL DEFAULT 800;
ALTER TABLE users
    ADD COLUMN blitz_elo INT NOT NULL DEFAULT 800;
ALTER TABLE users
    ADD COLUMN rapid_elo INT NOT NULL DEFAULT 800;

ALTER TABLE users
    ADD COLUMN been_2400_bullet BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users
    ADD COLUMN been_2400_blitz BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users
    ADD COLUMN been_2400_rapid BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
    ADD COLUMN bullet_games INT NOT NULL DEFAULT 0;
ALTER TABLE users
    ADD COLUMN blitz_games INT NOT NULL DEFAULT 0;
ALTER TABLE users
    ADD COLUMN rapid_games INT NOT NULL DEFAULT 0;